"""The language registry used to batch the author seed.

`language_id` is the ISO 639-1 code itself, referenced verbatim by the author
files and by the language seed (`assets/db/sql/language/language_0001.sql`,
generated by `iso_seed.py`). The English and native names fixed here take
precedence over the downloaded ones when the seed is regenerated.

Batch order matters: a writer working in several languages is emitted once, in
the batch of the first language of this list that claims them.
"""

from __future__ import annotations

# (ISO 639-1, Wikidata item, English name, native name)
LANGUAGES: list[tuple[str, str, str, str]] = [
    ("it", "Q652", "Italian", "Italiano"),
    ("en", "Q1860", "English", "English"),
    ("fr", "Q150", "French", "Français"),
    ("de", "Q188", "German", "Deutsch"),
    ("es", "Q1321", "Spanish", "Español"),
    ("pt", "Q5146", "Portuguese", "Português"),
    ("ru", "Q7737", "Russian", "Русский"),
    ("nl", "Q7411", "Dutch", "Nederlands"),
    ("pl", "Q809", "Polish", "Polski"),
    ("sv", "Q9027", "Swedish", "Svenska"),
    ("da", "Q9035", "Danish", "Dansk"),
    ("no", "Q9043", "Norwegian", "Norsk"),
    ("fi", "Q1412", "Finnish", "Suomi"),
    ("cs", "Q9056", "Czech", "Čeština"),
    ("hu", "Q9067", "Hungarian", "Magyar"),
    ("ro", "Q7913", "Romanian", "Română"),
    ("el", "Q9129", "Greek", "Ελληνικά"),
    ("tr", "Q256", "Turkish", "Türkçe"),
    ("ar", "Q13955", "Arabic", "العربية"),
    ("he", "Q9288", "Hebrew", "עברית"),
    ("fa", "Q9168", "Persian", "فارسی"),
    ("hi", "Q1568", "Hindi", "हिन्दी"),
    ("bn", "Q9610", "Bengali", "বাংলা"),
    ("ja", "Q5287", "Japanese", "日本語"),
    ("zh", "Q7850", "Chinese", "中文"),
    ("ko", "Q9176", "Korean", "한국어"),
    ("uk", "Q8798", "Ukrainian", "Українська"),
    ("ca", "Q7026", "Catalan", "Català"),
    ("sr", "Q9299", "Serbian", "Српски"),
    ("hr", "Q6654", "Croatian", "Hrvatski"),
    ("bg", "Q7918", "Bulgarian", "Български"),
    ("sk", "Q9058", "Slovak", "Slovenčina"),
    ("sl", "Q9063", "Slovene", "Slovenščina"),
    ("et", "Q9072", "Estonian", "Eesti"),
    ("lv", "Q9078", "Latvian", "Latviešu"),
    ("lt", "Q9083", "Lithuanian", "Lietuvių"),
    ("is", "Q294", "Icelandic", "Íslenska"),
    ("ga", "Q9142", "Irish", "Gaeilge"),
    ("eu", "Q8752", "Basque", "Euskara"),
    ("gl", "Q9307", "Galician", "Galego"),
    ("la", "Q397", "Latin", "Latina"),
    ("vi", "Q9199", "Vietnamese", "Tiếng Việt"),
    ("th", "Q9217", "Thai", "ไทย"),
    ("id", "Q9240", "Indonesian", "Bahasa Indonesia"),
    ("ms", "Q9237", "Malay", "Bahasa Melayu"),
    ("ta", "Q5885", "Tamil", "தமிழ்"),
    ("ur", "Q1617", "Urdu", "اردو"),
    ("af", "Q14196", "Afrikaans", "Afrikaans"),
    ("sw", "Q7838", "Swahili", "Kiswahili"),
    ("hy", "Q8785", "Armenian", "Հայերեն"),
    ("ka", "Q8108", "Georgian", "ქართული"),
    ("yi", "Q8641", "Yiddish", "ייִדיש"),
    ("eo", "Q143", "Esperanto", "Esperanto"),
]

BY_CODE = {row[0]: row for row in LANGUAGES}
